# Generated by Django 3.2.6 on 2021-10-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_rename_room_photo_rooma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='rooma',
            new_name='room',
        ),
    ]
